package com.ak.demo.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Fund implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private java.lang.String code;

    private java.lang.String marketValuePercentage;

    private java.lang.String name;

    public Fund() {
    }

    public java.lang.String getCode() {
        return this.code;
    }

    public void setCode(java.lang.String code) {
        this.code = code;
    }

    public java.lang.String getMarketValuePercentage() {
        return this.marketValuePercentage;
    }

    public void setMarketValuePercentage(java.lang.String marketValuePercentage) {
        this.marketValuePercentage = marketValuePercentage;
    }

    public java.lang.String getName() {
        return this.name;
    }

    public void setName(java.lang.String name) {
        this.name = name;
    }

    public Fund(java.lang.String code, java.lang.String marketValuePercentage,
            java.lang.String name) {
        this.code = code;
        this.marketValuePercentage = marketValuePercentage;
        this.name = name;
    }

}
